apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
    operators.operatorframework.io/builder: operator-sdk-v1.2.0
    operators.operatorframework.io/project_layout: go.kubebuilder.io/v2
  name: oracle-database-operator.v0.0.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: AutonomousDatabase is the Schema for the autonomousdatabases API
      displayName: Autonomous Database
      kind: AutonomousDatabase
      name: autonomousdatabases.database.oracle.com
      version: v1alpha1
    - description: DatabaseMetrics is the Schema for the autonomousdatabases API
      displayName: DatabaseMetrics
      kind: DatabaseMetrics
      name: databasemetrics.database.oracle.com
      version: v1alpha1
  description: Operator to manage Oracle sharding
  displayName: Oracle Sharding DB Operator
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - Oracle
  - sharding
  - db
  links:
  - name: Oracle Database Operator
    url: https://oracle-database-operator.domain
  maturity: alpha
  provider:
    name: ShardingDatabase
  version: 0.0.0
